version: '3.3'

# name: counters-dev

services:

  frontend:
    image: counters-frontend-dev
    build:
      context: ./counters-frontend
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - PORT_DEV=3000
    volumes:
      - ./counters-frontend/:/usr/src/app
    depends_on:
      - mongo
      - redis
    container_name: counters-frontend-dev

  backend:
    image: counters-backend-dev
    build:
      context: ./counters-backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - MONGO_URL_DEV=mongodb://root:pwd@counters-mongo-dev:27017/counters-dev
      - REDIS_URL_DEV=redis://counters-redis-dev:6379
    volumes:
      - ./counters-backend:/usr/src/app
    depends_on:
      - mongo
      - redis
    container_name: counters-backend-dev

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: counters-dev
    volumes:
      - ./counters-backend/mongo_data:/data/db
    container_name: counters-mongo-dev

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./counters-backend/redis_data:/data
    container_name: counters-redis-dev
